flags: {}
resolver: lts-13.26
extra-deps:
  - amazonka-1.6.1
  - amazonka-core-1.6.1
  - amazonka-ecr-1.6.1
  - amazonka-route53-1.6.1
  - amazonka-s3-1.6.1
  - amazonka-secretsmanager-1.6.1
extra-package-dbs: []
nix:
   packages: [zlib, bzip2]
